### PR TITLE
Data Handlers

### PR DESCRIPTION
**Pull request by tokejepsen**
https://github.com/pyblish/pyblish/pull/238

### CODE REVIEW

**Comment by mottosso** [comment]
A little cautious about the duplicated effort in toggling sections and toggling items alone, I would likely have the section toggling call upon the individual item toggling somehow. But we can deal with that later.

Looks good to me, any comments?

**Comment by tokejepsen** [comment]
> A little cautious about the duplicated effort in toggling sections and toggling items alone, I would likely have the section toggling call upon the individual item toggling somehow. But we can deal with that later.

Yeah, not fond of it either, but it works:)

**Comment by mottosso** [comment]
Success!

**Comment by tokejepsen** [comment]
Excellent:) Gunna start rolling it out here asap.

**Pull request merged**
