### PR TITLE
Added support for publish and validate from within the host app

### PR DESCRIPTION
**Pull request by liorbenhorin**
Looking for the best way to call pyblish_qml's window actions, like publish, validate, etc
In pylish_lite, we can simply do:
```
window = pyblish_maya.show()
window.publish() #after validation...
```
After chatting [here ](http://forums.pyblish.com/t/call-pyblish-qml-actions/388 )with @mottosso, 
Here's what i came up with.
Usage:

```
import pyblish_qml.host

pyblish_qml.host.publish()
pyblish_qml.host.validate()
```

### CODE REVIEW

**Comment by mottosso** [comment]
Whop! This looks very good to me. :)

Are you testing this? @tokejepsen would you be able to give this a test?

**Comment by tokejepsen** [comment]
This works :) And quite nicely as well!

@liorbenhorin could I ask your use-case for this? Why not use ```pyblish.api```?

**Comment by liorbenhorin** [comment]
Hi @tokejepsen!

My goal was to start the publish_qml and that the sequence will start automatically, without the user having to press anything.
Only if the test fails, then the GUI will remain open to see what went wrong.

If this can be achieved from `pyblish.api` i would love to know how :)

**Comment by tokejepsen** [comment]
> If this can be achieved from pyblish.api i would love to know how :)

You wouldn't be able to get the GUI as ```pyblish.api``` is all non-GUI, but you would be able to produce a report to your user of any validation failures.
I've been experimenting with this myself; https://github.com/tokejepsen/pyblish-grill-environment/blob/7230a561cfbbe419aeb8eebaad90282c62dc1512/environment/PYTHONPATH/grill_tools/nuke/pyblish_init.py#L123
Although when there is a validation failure, there user would have to go into the GUI anyways to maybe fix it with an action. Your solution here might be better :)

**Comment by tokejepsen** [comment]
I'm guessing your instances are already pre-enabled?

**Comment by mottosso** [comment]
I think @tokejepsen is referring to..

```python
from pyblish import util
context = util.publish()
```

Which then has an embedded report.

```python
for result in context["results"]:
  if not result["success"]:
    print("%s failed" % result["plugin"])

    for record in result["records"]:
      print(record.msg)
```

- [Reference](https://learn.pyblish.com/chapters/15-report-i.html)

**Comment by liorbenhorin** [comment]
@tokejepsen 
For now the usage is very basic, a single instance, say a character, being 'pushed' as a new master, so yeah, it's active (by enabled you mean active? I'm new here!)
I will make sure to look into your method soon!

@mottosso 
Yup, I'm aware of the non-gui method, and I'm using it for batch operations!

**Comment by tokejepsen** [comment]
> (by enabled you mean active? I'm new here!)

That's right :) You might run into problems when people wan't to pick'n'choose what to publish, but in your simple case this would work well.

**Comment by liorbenhorin** [comment]
@tokejepsen got it.
Yeah Iv'e got more complexed scenarios but they don't need to run automatically.

**Comment by tokejepsen** [comment]
Think we can merge this :)
@mottosso do you wanna do the honors?

**Comment by mottosso** [comment]
Happy to, but can someone up the version first? Then we can release this. :)

**Comment by liorbenhorin** [comment]
@mottosso done

**Comment by mottosso** [comment]
Thanks @liorbenhorin!

**Comment by tokejepsen** [comment]
Missing a release for this :)

**Comment by mottosso** [comment]
Indeed, setting one up now.

**Pull request merged**
