### PR TITLE
Implement #227 

### PR DESCRIPTION
**Pull request by mottosso**
Alert the window on `controller.finished signal`

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks @BigRoy, should we try and get the balloon popup in there as well? Or better save that for a next PR?

**Comment by BigRoy** [comment]
This is working great as a minor feature actually, because of its simplicity I assume this could be part of a patch version and separate out the notification. I'm expecting that to have some discussion along the way, regarding how long it stays, design, what's messaged in it and how. That would mean this minor feature will only be waiting longer than needed (and could stay off from merging until we've gone fully through the notification feature).

How about renaming #227 to _alert user on completion_ and make a new issue regarding _show notification pop-up upon completion_ to really have them separated?

**Comment by mottosso** [comment]
> How about renaming #227 to alert user on completion and make a new issue regarding show notification pop-up upon completion to really have them separated?

Agreed, this is such a simple and small modification that it stands well on its own.

**Comment by mottosso** [comment]
Version up please?

**Comment by BigRoy** [comment]
I happened to have merged with this repo just now, and added something to .gitignore.

**Comment by mottosso** [comment]
No problem.

**Pull request merged**
