### PR TITLE
Update Qt.py to 1.1.0.b10.

### PR DESCRIPTION
**Pull request by tokejepsen**
I had an issue where PySide where not being picked up:

```python
import os
os.environ["QT_VERBOSE"] = "True"
# Result: import pyblish_qml
pyblish_qml.show()
# Result: C:\Program Files\Nuke10.5v6\Nuke10.5.exe
Preferred bindings: ['_pyside2', '_pyqt5', '_pyside', '_pyqt4']
Trying _pyside2
ImportError: No module named PySide2
Trying _pyqt5
ImportError: No module named PyQt5
Trying _pyside
ImportError: DLL load failed: The specified module could not be found.
Trying _pyqt4
ImportError: No module named sip
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\admin\development\installation\windows\envs\bumpybox-environment\Lib\site-packages\repositories\pyblish-qml\pyblish_qml\__init__.py", line 11, in show
    from . import host
  File "C:\Users\admin\development\installation\windows\envs\bumpybox-environment\Lib\site-packages\repositories\pyblish-qml\pyblish_qml\host.py", line 9, in <module>
    from .vendor.Qt import QtWidgets, QtCore, QtGui
  File "C:\Users\admin\development\installation\windows\envs\bumpybox-environment\Lib\site-packages\repositories\pyblish-qml\pyblish_qml\vendor\Qt.py", line 359, in <module>
    raise ImportError("No Qt binding were found.")
ImportError: No Qt binding were found.
```

Updating Qt.py

### CODE REVIEW

**Comment by tokejepsen** [comment]
The failed tests seem to be a Docker issue. Ran the tests without Docker locally with success.

**Comment by mottosso** [comment]
It's a Docker issue; all of my Ubuntu images have started failing since the new year..

**Comment by tokejepsen** [comment]
Did you figure out what the issue was?

**Comment by mottosso** [comment]
Yes, all fixed. Merge ahead.

**Pull request merged**
