### PR TITLE
fix for #25

### PR DESCRIPTION
**Pull request by tokejepsen**

### CODE REVIEW

**Comment by mottosso** [comment]
Don't forget to include an image of what it looks like if it's a graphical change, so it's easier to evaluate.

**Comment by tokejepsen** [comment]
Here we are:)

capture

**Comment by mottosso** [comment]
Thanks. :)

I think the blue color is a bit sharp on the eyes against the gray background.. What do you think? Is that anything we could have a look at changing?

**Comment by tokejepsen** [comment]
> What do you think? Is that anything we could have a look at changing?

My thoughts exactly, but that is pure html code in the text. This would be up to the user to change that. When the user just adds text based links, they will be converted to the white colour seen on ```http://pyblish.com```

**Comment by mottosso** [comment]
I was thinking we could alter the default colors, via QML "Styles". A component you add to another component to govern how it looks

For example, here's how a default button can be modified.

- https://doc.qt.io/qt-5/qml-qtquick-controls-styles-buttonstyle.html

However, after some quick googling, it looks like there aren't any text components to modify the default colors of hyperlinks..

Since you're already doing string substitution, what do you think about defaulting the look of <a> tags to white as well? Basically ignoring whatever color is passed in (discouraging the use of multiple colors) and assuming none was present.

I think consistency here more expected than getting different colors for links you hard-code from those you don't.

**Comment by tokejepsen** [comment]
> Since you're already doing string substitution, what do you think about defaulting the look of tags to white as well?

We could do, but I thinking that if someone is using html code there is a definite intent on something specific. It would then be very confusing if they get something they don't expect.

**Comment by mottosso** [comment]
To be honest, I think the HTML tags in a Python docstring looks terrible and I think it's something we should discourage all together.

If you want a clickable link, just put http:// or https:// in front of it. That way, we still conform to docstring syntax and don't encourage further mutilation with more HTML tags, because that can get real ugly real fast.

**Comment by tokejepsen** [comment]
Cool, don't need to do anything then:)

**Comment by mottosso** [comment]
Haha, I suppose not. We'll simply not advertise the ability to use HTML. There is another reason for avoiding that too, which is that the Text component is severely limited in the amount of tags it supports. Once we start advertising HTML functionality, a lot of requests for missing functionality is bound to appear; better save that for something that actually supports HTML or roll our own parser (like Markdown-to-QML).

**Comment by mottosso** [comment]
Kickass work @tokejepsen, I don't even recognize Pyblish anymore, it's so much better already. :)

**Comment by tokejepsen** [comment]
Thanks:) got a couple of issues out of the way with some downtime here.

**Pull request merged**
