### PR TITLE
Plugin section toggling

### LINKED ISSUE #139: Clicking section for plug-ins has no effect
In [a recent update](https://github.com/pyblish/pyblish-qml/pull/138), clicking sections was introduced. But only for instances. We'll need to either disable feedback for plug-ins, or add support there as well.

### PR DESCRIPTION
**Pull request by tokejepsen**
Fixes #139

### CODE REVIEW

**Comment by mottosso** [comment]
Sweeeeet. :)

**Comment by mottosso** [comment]
Would you mind if I delayed pushing this to Win immediately? It's a bit of a process to increment its version and produce another build and is better suited for collections of features than single ones such as this.

**Comment by tokejepsen** [comment]
Yeah, I don't mind. I've got individual repos setup here, so I can just update whenever.

**Comment by mottosso** [comment]
Ah, excellent!

**Pull request merged**
