### PR TITLE
Work in progress of new ID-based items

### PR DESCRIPTION
**Pull request by mottosso**
GUI works, but some tests fail!

### CODE REVIEW

**Comment by BigRoy** [comment]
Thanks a ton. Is it mainly test changes from this point?

**Comment by BigRoy** [comment]
Will have a quick look on my end with this.

**Comment by mottosso** [comment]
> Is it mainly test changes from this point?

Possibly, but we're probably not out of the woods yet. The tests might reveal a flaw somehow.

**Comment by BigRoy** [comment]
It was purely on IDs -> names, not something else. See my [PR](https://github.com/mottosso/pyblish-qml/issues/1). Ran this version through a quick scene as well and seems to work (just quickly tested) including the actions.

**Pull request merged**
