### PR TITLE
Hide section

### PR DESCRIPTION
**Pull request by tokejepsen**
This PR is an attempt at being able to hide sections of items in the UI. This is just the basic working version, so everything is up for discussion.

dec 8 2017 12_23 pm

Its implemented similar to how the toggling works, by having a ```item.isHidden``` property in the model. I'm thinking that this will allow us to implement a way to customize which sections are shown on launch, which could address https://github.com/pyblish/pyblish-qml/issues/189

### CODE REVIEW

**Comment by tokejepsen** [comment]
I see I have #273 in here as well. Maybe we could merge that first, instead of having to reopen a PR.

**Comment by BigRoy** [comment]
The behavior to click the header and toggle all instances underneath it? Is that still doable? If so, how does one do that now? You seem to do it in the GIF but I'm not sure how.

**Comment by BigRoy** [comment]
Also, I think it's looking good. But with the headers being able to collapse I must say when they are collapsed it's confusing if one of the stages gave errors, because you wouldn't see it. As such the headers must likely become much more informative to in a way allow showing such data? Or would it always show warned/errored plug-ins?

**Comment by tokejepsen** [comment]
> You seem to do it in the GIF but I'm not sure how.

Yup, you can still do that. The clickable area is the labels boundary. Just the first solution I could think off, so suggestions for better alternatives are welcome.

> Or would it always show warned/errored plug-ins?

Yeah, I was thinking we could colour the label depending on the succcess/failed state. Similar to how the instance items checkbox colouring works.

**Comment by BigRoy** [comment]
> Yup, you can still do that. The clickable area is the labels boundary. Just the first solution I could think off, so suggestions for better alternatives are welcome.

Ah, I see. Maybe CTRL + click makes more sense to maybe toggle all.

> Yeah, I was thinking we could colour the label depending on the succcess/failed state. Similar to how the instance items checkbox colouring works.

Could be a good start yes.

**Comment by tokejepsen** [comment]
Forgot to show processing:

**Comment by mottosso** [comment]
Wow! This is amazing! There was a request a while back about optionally hiding collectors, as they didn't provide much value to the artist. Maybe some sections could be collapsed per default somehow? Maybe just hardcode the collectors.

**Comment by mottosso** [comment]
Ah, you linked to it, it's https://github.com/pyblish/pyblish-qml/issues/189 :) Perfect.

**Comment by tokejepsen** [comment]
> Maybe some sections could be collapsed per default somehow?

I was thinking we could query for a ```hidden``` data member/attribute, similar to how you can set the ```publishable``` state of an instance. This would makes it very flexible and allow us to hide any section and even let the user customize which section should be hidden.

**Comment by BigRoy** [comment]
> I was thinking we could query for a hidden data member/attribute, similar to how you can set the publish state of an instance. This would makes it very flexible and allow us to hide any section and even let the user customize which section should be hidden.

Actually, it's not similar - because this would be for the complete section not _per instance_ or _per plugin_. We've never stored data for a grouped section before I believe?

**Comment by davidlatwe** [comment]
> Ah, I see. Maybe CTRL + click makes more sense to maybe toggle all.

Just interesting in this :)
Maybe make the `v` arrow mark into a circular and rotatable checkbox for toggle all ?
Providing both hide/show and all on/off visual hint.

**Comment by tokejepsen** [comment]
> Maybe make the v arrow mark into a circular and rotatable checkbox for toggle all ?

That is an interesting idea :) Never seen something like that before. Slightly worry would be that user aren't familiar with it. Have you got a reference for this from somewhere?

**Comment by tokejepsen** [comment]
> We've never stored data for a grouped section before I believe?

Actually when I think about this some more, it might become too confusing to have some plugins/instance hidden within a section because there is no indication for hidden items.

Maybe its better to expose a public list of sections labels to hide on startup.
```python
import pyblish_qml import settings

settings.HiddenSections = ["Collect"]
```

**Comment by BigRoy** [comment]
> > Maybe make the v arrow mark into a circular and rotatable checkbox for toggle all ?
>
> That is an interesting idea :) Never seen something like that before. Slightly worry would be that user aren't familiar with it. Have you got a reference for this from somewhere?

Also not sure how clear that would be for plug-ins, because there are often only a few which can be toggled. So there would always be a remainder that is enabled - what would it then show? :)

**Comment by tokejepsen** [comment]
> what would it then show?

Good point, that might become confusing.

We could also just rethink where/how to hide a section. I initially thought of have just the arrow ```>``` be clickable, but that seemed like a very small area to hit with the cursor.

**Comment by davidlatwe** [comment]
> Slightly worry would be that user aren't familiar with it.

Yeah, it might :( . Most case I know they always separate the function of tree collapsing and toggling, and visualize both.
Currently only have one persist visual item (`v` arrow mark) in there to give the collapsible hint, and the toggle all is implicit. Maybe should add one more indicator for keeping those options visualize ?
Or just leave it as is ? Since at least me personally not often need to toggle them all : /

**Comment by davidlatwe** [comment]
> We could also just rethink where/how to hide a section.

Yes, right. Maybe use `+` and `-` for collapsing ? For differentiate from *go to perspective*

**Comment by tokejepsen** [comment]
> For differentiate from go to perspective

Good point as well.

Here is an option for separating the collapsing and toggling:

dec 8 2017 2_39 pm

**Comment by tokejepsen** [comment]
This is starting to feel right :)

dec 8 2017 2_57 pm

**Comment by davidlatwe** [comment]
This might be another issue.
For showing the plugin's toggle status if the section is collapsed, how about something like github's modification indicator or deadline's progress bar ?
Darker color would be the *can not toggle*, mid-gray would be *off*, white for *on*, and turn in to progress bar when processing.

status-bar
status-bar-2

maybe won't need number on it, just use color as a simple visual hint.

**Comment by tokejepsen** [comment]
> maybe won't need number on it, just use color as a simple visual hint.

I'm going to try and adhere to the current color scheme and processing indicator. That being when processing the section label will highlight (blink), and on success color the label (and/or the icon) green, on warning=orange and failed=red.

Progress bar is a different issue all together :)

**Comment by tokejepsen** [comment]
I've hardcoded the "Collect" section to be collapsed. While trying to update the UI from the controller and looking into what is required from getting the colours working when processing, it seems to me that we'll need to have a dedicated "section" in the model.

I'll return to this on Monday, but if anyone has any ideas please chime in.

**Comment by mottosso** [comment]
This is really great work!

> it seems to me that we'll need to have a dedicated "section" in the model.

On playing with this, I noticed that the icon sometimes got confused as to whether a section was expanded or not, also the sections that appear twice, like `MyFamily` is doubly confused. So yes, I think you're right, we need some way of keeping track of state outside of the GUI.

I made some cosmetics suggestions, let me know what you think.

untitled project

**Comment by mottosso** [comment]
A *hint* of depth. :) Similar to the other "3d" effects.

untitled project

**Comment by tokejepsen** [comment]
Struggling a bit to figure out how to assign a section an item in the model to reference values from.

If anyone has some ideas, please let me know.

**Comment by tokejepsen** [comment]
Think I have got a working solution for having sections in the model. Still need to see how it handles changing colour on processing.

If anyone has any feedback on the code, please rip it apart cause I'm unsure about it.

**Comment by tokejepsen** [comment]
Alright, another version to review :)

dec 11 2017 4_22 pm

Personally I think we may be suffering from information overload now, but could also just be because I'm used to the old amount of information.
Maybe colouring the show/hide button is better?

dec 11 2017 4_30 pm

**Comment by davidlatwe** [comment]
Maybe this would help ?
Just tweak a little bit, shrink down the label and tint the border

qml_demo

**Comment by tokejepsen** [comment]
Thats nice @davidlatwe :) I could run with that. Anyone else have an opinion on this?

@davidlatwe guessing you that as code?

**Comment by davidlatwe** [comment]
Yes, it does :D
But I think I am not able to add into this PR, maybe I push to my fork for you to see the changes.

**Comment by tokejepsen** [comment]
> But I think I am not able to add into this PR, maybe I push to my fork for you to see the changes.

Yeah, if you push the changes to your fork and PR to my ```hide_section``` branch, then I can just merge it.

**Comment by davidlatwe** [comment]
Okay, it's done :)

**Comment by BigRoy** [comment]
Woot, that last one is sweet! Does it also turn orange on only warnings? Taking over the highest level of status? 

Maybe even green if it's fully complete? (So you know it has processed?) Or might be too much visual clutter.

Awesome stuff.

**Comment by tokejepsen** [comment]
> Woot, that last one is sweet! Does it also turn orange on only warnings? Taking over the highest level of status?

It does indeed :) Same as how the checkboxes work.

> Maybe even green if it's fully complete? (So you know it has processed?) Or might be too much visual clutter.

I'll try it tomorrow :)

**Comment by davidlatwe** [comment]
> Does it also turn orange on only warnings?

image support :D

warning

**Comment by davidlatwe** [comment]
<details>
<summary>Add some warning case to family "failure" and "B"</summary>
<br>

demo
</details>

I thought this should be in another PR, so I committed this one on a [new branch](https://github.com/davidlatwe/pyblish-qml/commit/412bfd55e32d459b3c2537f23d1af2750ed4185d) based on `master` branch.
Let me know if you want this, should be easy to merge :)

**Comment by mottosso** [comment]
This makes me want to find something to publish with failures and warnings all over the place. So pretty. :) Great work guys.

**Comment by tokejepsen** [comment]
> Let me know if you want this, should be easy to merge

Sure, lets just get this in as well :)

**Comment by tokejepsen** [comment]
This is with colouring the succeeded section green:

dec 12 2017 10_22 am

What do we think?

**Comment by mottosso** [comment]
> What do we think?

It's definitely a lot, I'll need to look at it a few times to tell whether it feels off because it's new or because it's too much.

**Comment by mottosso** [comment]
Could you post a full-sized gif of it, to get the full experience?

**Comment by davidlatwe** [comment]
Maybe dim out a little `successColor` from `#77AE24` to like `#687F5E` would help ?

dim

**Comment by tokejepsen** [comment]
> Could you post a full-sized gif of it, to get the full experience?

dec 12 2017 11_49 am

> Maybe dim out a little successColor from #77AE24 to like #687F5E would help?

Think if we are going that dark with the green, we might as well just keep it grey like before.

**Comment by mottosso** [comment]
Ok, I think I've got it.

I think the added green obscures the more important color, red. If nothing is red, I think I would read that as "No problem".

Now with so much green, the same information appears twice, loudly - "No problem, ALL GOOD!". Let's keep green to a minimal, like it was, but keep the red. Screaming more loudly on error - e.g. "SOMETHING BAD!" - is a good thing. :)

**Comment by tokejepsen** [comment]
Agree :)

capture

**Comment by tokejepsen** [comment]
Any other thoughts on this?

Think we are ready for a merge else.

**Comment by mottosso** [comment]
I'm all out. If everyone else is happy, merge at will!

**Comment by BigRoy** [comment]
I personally feel the dimmed out green for success could be useful as indication, because if it's collapsed there would otherwise not be any way to "know" whether something would've been processed or not. For example, on reset... the Collectors would already be green - (red in the example because it has a failing one).

But for now I think the gray one is a good start that feels less cluttered - let's see if we ever end up missing it.

**Comment by BigRoy** [comment]
I believe visually it looks good. In code I'm not so sure - to me this seems confusing:

https://github.com/pyblish/pyblish-qml/pull/275/files#diff-ac156cba73ac1ef385b357bbfc21d258R484

Why is it taking the "hideState" but not using it?

**Comment by mottosso** [comment]
Good catch. That if-structure could be condensed some.

About the green, would it make more sense to only color a section if it is closed? Then they could be either green or red, as they'd be the only indicator of success or failure.

**Comment by tokejepsen** [comment]
> Why is it taking the "hideState" but not using it?

Nice catch! Fixed it now. Was working because it was assuming the opposite state was desired, which was the case in most scenarios.

**Comment by BigRoy** [comment]
> About the green, would it make more sense to only color a section if it is closed? Then they could be either green or red, as they'd be the only indicator of success or failure.

Hmm, I don't think that's much better. I kind of like it clearly highlighting the status as it is.

**Comment by tokejepsen** [comment]
> About the green, would it make more sense to only color a section if it is closed?

That is interesting. Here it is in practise:

dec 12 2017 4_46 pm

**Comment by mottosso** [comment]
I think that looks fantastic. Minimalist, unambiguous. This gets my vote!

**Comment by mottosso** [comment]
Looking back..



I do like the darkness of the sections in this one, and the fact that the button isn't highlighted by default.

Let's give this another day or so to sink in before merging.

**Comment by mottosso** [comment]
The very first entry is also not bad..



Definitely needs a day or so. :)

**Comment by BigRoy** [comment]
I'd say let's try to roll out this one: https://github.com/pyblish/pyblish-qml/pull/275#issuecomment-351095335

With the color states only on collapsed - if that's in, or whatever we decide on for the first version, then I'll roll it out to the team soon and see what they have to say.

**Comment by davidlatwe** [comment]
Hi, sorry, just adding one opinion :) 
> I do like the darkness of the sections in this one

I actually like the brightness of sections stay close with background color though, I think/feel that leaves the main contrast stay on those instances and plugins (gray and white), like introducing this new section style/function in a little smooth way.

**Comment by mottosso** [comment]
I've pushed a small change, with a little less contrast.

untitled project

However I do still like the subtleness and clarity of [this one](https://user-images.githubusercontent.com/1860085/33838810-dedc43c6-de90-11e7-9c97-5b8e9c50f138.gif).

**Comment by BigRoy** [comment]
> I've pushed a small change.

I'm liking this. :)

**Comment by tokejepsen** [comment]
Not to fuel the fire, but this is my candidate:

dec 13 2017 10_48 am

This is based on introducing only what is needed:
- Sections stay the same unless hidden, which is a newly introduced feature, hence needing additional UI features to accommodate.
- Minimal amount of visuals when sections are hidden. Although colouring just the hide/show button is not enough, but colouring the text compromises the readability of the text.

Direct comparison with current master:

old
new

**Comment by mottosso** [comment]
Could you try that @tokejepsen, but without the surrounding rectangle on the section? Just coloring the + button, similar to the checkboxes.

**Comment by tokejepsen** [comment]
> but without the surrounding rectangle on the section?

dec 13 2017 11_09 am

**Comment by davidlatwe** [comment]
This is the best to me !!

**Comment by mottosso** [comment]
Happy to try this, so we can let it simmer in production for a few weeks and potentially return to this great wall of alternative designs if necessary.

**Comment by tokejepsen** [comment]
I'd be happy with this as well :)

Least amount of visual change. Then gather opinions from production for further refinement.

**Comment by BigRoy** [comment]
I'm slightly afraid the warnings might not be visible enough in the last version. And also maybe not clear enough that they are "container headers".

But let's give it a go.

**Comment by mottosso** [comment]
Welcome to merge and release (quick! Before someone else comments on it! ;) )

**Comment by tokejepsen** [comment]
Shit! Too fast, forgot to add the latest changes.

**Comment by mottosso** [comment]
Haha! Sorry to rush you! :D

**Pull request merged**
