### PR TITLE
Persist status text until next event.

### PR DESCRIPTION
**Pull request by tokejepsen**
dec 6 2017 3_12 pm

### CODE REVIEW

**Comment by BigRoy** [comment]
Yes, this looks good. Now looking at the messages they might be confusing.

When clicking validate, it says: `publishing..` - should this read `validating..`?
When clicking publish, it says: `publishing..` - perfect!

When clicking validation and it finishes it says: `Finished..`
When clicking publish and it finished it says; ` Finished..`
The end is ambiguous. Both might be confusing as to what could've happened.
Should those respectively read ``Finished validation..` and `Finished publish..` - or does that alter to much logic?

**Comment by tokejepsen** [comment]
> Now looking at the messages they might be confusing.

I agree. Currently though this would require quite a bit more development. Might be better left for a separate issue/PR.

Adding to this, it might be nice to have the status display the stages its going through; ```collecting...``` > ```Finished collection.``` > ```validating...``` > ```extracting...``` > ```integrating...``` > ```Finished.```

**Comment by BigRoy** [comment]
Yes, separate issue sounds good.

**Comment by tokejepsen** [comment]
Done :) https://github.com/pyblish/pyblish-qml/issues/274

**Comment by mottosso** [comment]
I'm happy to merge this, can work out details after the fact. Fire at will!

**Comment by BigRoy** [comment]
Let's do this!

**Pull request merged**
