### PR TITLE
adding in support for WindowPosition

### PR DESCRIPTION
**Pull request by Coyode**
Adding to host to allow window to be positioned in the settings on startup

### CODE REVIEW

**Comment by mottosso** [comment]
Thanks @Coyode! Would you mind limiting the line length to 79 characters? That would be fantastic!

**Comment by Coyode** [comment]
Sure! Just working out how to make that change on top of my already made change.... Not used to github lol

**Comment by mottosso** [comment]
You can simply make the change, commit, push to your own repository again, and this PR will automagically update. :)

**Comment by tokejepsen** [comment]
This got support with a different PR; https://github.com/pyblish/pyblish-qml/pull/235, so we can close this?

**Comment by mottosso** [comment]
That's true, thanks.

**Pull request closed without merging**
